// <auto-generated />
namespace Leikjavefur.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class UltramegaOK : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UltramegaOK));
        
        string IMigrationMetadata.Id
        {
            get { return "201305031641432_UltramegaOK"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
